### ISSUE TITLE
Integrate into docker compose 

### ISSUE THREAD

**Issue by chrisheib** [vincss/mcsleepingserverstarter#109]
Hey there, I got a simple server running with docker compose, like this:

```
version: "3"

services:
  mc:
    container_name: walkercraft
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      MEMORY: "2500M"
      TYPE: FABRIC
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      - ./data:/data
      - ./mods:/mods
```

Is there any way to quickly include the sleepingserverstarter, optimally as separate compose service?
