### ISSUE TITLE
Waking up message issues

### ISSUE THREAD

**Issue by alexlogvin** [vincss/mcsleepingserverstarter#131]
When I'm trying to connect to a server in sleeping mode, I expect to see `loginMessage:` (from `sleepingSettings.yml`) but instead it gives me this error, and starts the server.

```log
Internal Exception:
io.netty.handler.codec.DecoderException:
java.lang.IndexOutOfBoundsException:
readerIndex(58) + length(1) exceeds writerIndex(58):
PooledUnsafeDirectdyteduf(ridx: 58, widx: 58, cap: 58/59)
```

In game example:
![image](https://user-images.githubusercontent.com/6129602/206989966-475359e6-399d-4fd8-90c4-85f2fe7c6123.png)

`log/sleepingServer.log`:
```
2022-12-12 08:38:41 info: A Prince has taken a quick peek. [handshaking_1.19] 
2022-12-12 08:38:41 info: Prince [AlteX.play] has come, time to wake up. 
2022-12-12 08:38:41 info: Sending best regards ...Waking server up, come back in a minute... 
2022-12-12 08:38:42 info: [AlteX] The prince is gone, for now 
```

`sleepingSettings.yml`:
```yml
serverName: Home server                                                    [Sleeping]
serverPort: 25565
version: 1.19.2
favIcon: data:image/png;base64,iVBORw0KGgoAAA... (truncated because it's too long)
bedrockPort: 0
maxPlayers: 20
loginMessage: ...Waking server up, come back in a minute...
serverOnlineMode: false
webPort: 0
webStopOnStart: false
startMinecraft: true
minecraftCommand: run.bat
```

System info:
```
OS Name:	Microsoft Windows 10 Enterprise
Version:	10.0.19045 Build 19045
Processor:	11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz, 1690 Mhz, 4 Core(s), 8 Logical Processor(s)
RAM:		16.0 GB
