### ISSUE TITLE
Many Princes are taking peeks (Server keeps `handshaking_1.16.5`)

### ISSUE THREAD

**Issue by Stonewall0210** [vincss/mcsleepingserverstarter#29]
There is a problem with the server in sleeping mode where it continuously prints out `A Prince has taken a quick peek. [handshaking_1.16.5]`

I am using the commit 31bb50f (as far as I'm aware, I forgot to keep track), this is my config
```yml
# sleepingSettings.yml
serverName: Server Sleeping. Join to wake!
serverPort: 25566
bedrockPort:
loginMessage: The server is waking up. Please try again in a bit!
serverOnlineMode: false
webPort:
webDir:
startMinecraft: 1
minecraftCommand: java -jar paper-1.16.5-592.jar nogui
```
This is happening with the two instances of this that I have running at a time, the other config isn't much different
```yml
# sleepingSettings.yml
serverName: Server Sleeping. Join to wake!
serverPort: 25567
bedrockPort:
loginMessage: The server is waking up. Please try again in a bit!
serverOnlineMode: false
webPort: 8100
webDir:
startMinecraft: 1
minecraftCommand: java -jar paper-1.16.5-572.jar nogui
```
None of the ports used are forwarded since I am using BungeeCord and using the sleeping servers to take a load off of the host computer when the servers don't have any players
If I need to provide more info please tell me.
